import random

carreras_universitarias = [
    "Administración de Empresas",
    "Antropología",
    "Arquitectura",
    "Arte",
    "Biología",
    "Ciencias Ambientales",
    "Ciencias de la Computación",
    "Ciencias Políticas",
    "Comunicación Social",
    "Contaduría Pública",
    "Derecho",
    "Diseño Gráfico",
    "Economía",
    "Educación",
    "Enfermería",
    "Física",
    "Geografía",
    "Historia",
    "Ingeniería Agrícola",
    "Ingeniería Ambiental",
    "Ingeniería Biomédica",
    "Ingeniería Civil",
    "Ingeniería de Alimentos",
    "Ingeniería de Minas",
    "Ingeniería de Sistemas y Computación",
    "Ingeniería Eléctrica",
    "Ingeniería Industrial",
    "Ingeniería Mecánica",
    "Ingeniería Química",
    "Lenguas Modernas",
    "Matemáticas",
    "Medicina",
    "Microbiología",
    "Música",
    "Nutrición y Dietética",
    "Odontología",
    "Pedagogía",
    "Psicología",
    "Química",
    "Sociología",
    "Trabajo Social",
    "Arquitectura Paisajista (Maestría)",
    "Biología Molecular y Biotecnología (Maestría)",
    "Ciencias de la Información y la Comunicación (Maestría)",
    "Desarrollo Sostenible (Maestría)",
    "Economía (Maestría)",
    "Educación (Maestría)",
    "Estudios Latinoamericanos (Maestría)",
    "Física (Maestría)",
    "Genética y Biología Molecular (Maestría)",
    "Gestión y Desarrollo Urbanos (Maestría)",
    "Historia (Maestría)",
    "Ingeniería Biomédica (Maestría)",
    "Ingeniería Civil y Ambiental (Maestría)",
    "Ingeniería de Materiales (Maestría)",
    "Ingeniería de Sistemas y Computación (Maestría)",
    "Lingüística (Maestría)",
    "Matemáticas (Maestría)",
    "Música (Maestría)",
    "Neurociencias (Maestría)",
    "Odontología (Maestría)",
    "Planificación Urbana y Regional (Maestría)",
    "Química (Maestría)",
    "Salud Pública (Maestría)",
    "Sociología (Maestría)",
    "Trabajo Social (Maestría)",
    "Arquitectura (Doctorado)",
    "Biología (Doctorado)",
    "Ciencias de la Información y la Comunicación (Doctorado)",
    "Derecho (Doctorado)",
    "Educación (Doctorado)",
    "Estudios Urbanos y Regionales (Doctorado)",
    "Física (Doctorado)",
    "Ingeniería Civil (Doctorado)",
    "Lingüística (Doctorado)",
    "Matemáticas (Doctorado)",
    "Medicina (Doctorado)",
    "Neurociencias (Doctorado)",
    "Química (Doctorado)",
    "Sociología (Doctorado)"
]


for i in range(1000):
    idx = random.randint(0, len(carreras_universitarias)-1)
    print(carreras_universitarias[idx])
